using System.Collections.ObjectModel;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Ecad.Core.Models;
using Ecad.Data;

namespace Ecad.App.ViewModels;

/// <summary>A Device+Pin pair flattened for combo-box display in the Connections grid's from/to pickers.</summary>
public sealed record DevicePinOption(long PinId, string Label);

/// <summary>
/// M8 Connections grid (Section 6.2): edit connections — from-pin, to-pin, color, cross-section,
/// length, cable/core assignment — without drawing. Per ADR-011, this grid does NOT create new
/// Connections — a Connection is only generated by drawing/auto-connecting on the canvas (mimicking
/// EPLAN's graphics-first workflow); the From/To Pin columns below let you re-wire an EXISTING
/// connection's endpoints, not conjure a new one out of nothing. Per ADR-015, it does not delete
/// Connections either — unlike a Device or Cable (parts with independent identity), a Connection is
/// purely a derived fact of two placements' geometry, so the only way to remove one is to change
/// that geometry on the canvas (move the symbols apart, or delete the wire there). Deliberately does
/// not surface any ConnectionEnd/termination columns — that's the separate Terminations tab
/// (TerminationsGridViewModel, M9), which edits the same ConnectionEnd rows CreateConnection already
/// populates here (termination off) with a dedicated filterable/bulk-assign view of its own.
/// </summary>
public sealed partial class ConnectionsGridViewModel : ObservableObject
{
    private readonly ProjectSession _session;

    public ObservableCollection<Connection> Connections { get; } = [];
    public ObservableCollection<Connection> SelectedConnections { get; } = [];
    public ObservableCollection<DevicePinOption> AllDevicePins { get; } = [];
    public ObservableCollection<Cable> AllCables { get; } = [];

    /// <summary>Connections with an attached definition point — their Color/Cross-section are set via
    /// the canvas (mirrored one-way from the definition point) and become read-only here, the same
    /// treatment Wire# already gets, for the same reason. Refreshed alongside Connections.</summary>
    public HashSet<long> ConnectionIdsWithDefinitionPoint { get; } = [];

    /// <summary>Connections crossed by a cable definition line — their Cable/Core are set via the
    /// canvas and become read-only here, same "set via canvas" treatment as ConnectionIdsWithDefinitionPoint.</summary>
    public HashSet<long> ConnectionIdsWithCableLineCrossing { get; } = [];

    [ObservableProperty]
    private Dictionary<long, List<CableCore>> _coresByCableId = [];

    [ObservableProperty]
    private string? _bulkColor;

    [ObservableProperty]
    private double? _bulkCrossSectionMm2;

    public ConnectionsGridViewModel(ProjectSession session)
    {
        _session = session;
        RefreshDevicePinOptions();
        RefreshCableOptions();
        Refresh();
    }

    public void Refresh()
    {
        Connections.Clear();
        foreach (var connection in _session.GetAllConnections()) Connections.Add(connection);

        ConnectionIdsWithDefinitionPoint.Clear();
        foreach (var connectionId in _session.GetConnectionIdsWithDefinitionPoint()) ConnectionIdsWithDefinitionPoint.Add(connectionId);

        ConnectionIdsWithCableLineCrossing.Clear();
        foreach (var connectionId in _session.GetConnectionIdsWithCableLineCrossing()) ConnectionIdsWithCableLineCrossing.Add(connectionId);
    }

    /// <summary>Rebuilds the from/to pin picker options — called on ProjectSession.PlacementsChanged
    /// (a Device or its pins may have changed) in addition to this grid's own device edits.</summary>
    public void RefreshDevicePinOptions()
    {
        AllDevicePins.Clear();
        foreach (var device in _session.GetAllDevices())
        {
            var tag = FormatDeviceTag(device);
            foreach (var pin in _session.GetDevicePins(device.Id))
                AllDevicePins.Add(new DevicePinOption(pin.Id, $"{tag} — {pin.Name}"));
        }
    }

    /// <summary>Rebuilds the Cable/CableCore picker options — called on ProjectSession.CablesChanged.</summary>
    public void RefreshCableOptions()
    {
        AllCables.Clear();
        var coresByCableId = new Dictionary<long, List<CableCore>>();
        foreach (var cable in _session.GetAllCables())
        {
            AllCables.Add(cable);
            coresByCableId[cable.Id] = _session.GetCableCores(cable.Id).ToList();
        }
        CoresByCableId = coresByCableId;
    }

    private static string FormatDeviceTag(Device device)
    {
        var prefix = string.Empty;
        if (!string.IsNullOrEmpty(device.FunctionSegment)) prefix += $"={device.FunctionSegment} ";
        if (!string.IsNullOrEmpty(device.LocationSegment)) prefix += $"+{device.LocationSegment} ";
        return $"{prefix}-{device.DeviceTagSegment}";
    }

    [RelayCommand(CanExecute = nameof(HasSelection))]
    private void BulkSetColor() =>
        _session.BulkUpdateConnectionColor(SelectedConnections.Select(c => c.Id).ToList(), BulkColor);

    [RelayCommand(CanExecute = nameof(HasSelection))]
    private void BulkSetCrossSection() =>
        _session.BulkUpdateConnectionCrossSection(SelectedConnections.Select(c => c.Id).ToList(), BulkCrossSectionMm2);

    private bool HasSelection() => SelectedConnections.Count > 0;

    public void NotifySelectionChanged()
    {
        BulkSetColorCommand.NotifyCanExecuteChanged();
        BulkSetCrossSectionCommand.NotifyCanExecuteChanged();
    }

    /// <summary>Called by the view after a DataGrid row edit commits — Connection has plain
    /// properties, so nothing persists the in-memory edit to SQLite without this. Color/Cross-section
    /// are skipped (and reverted via Refresh) for a row with an attached definition point, and Cable/
    /// Core are skipped (and reverted) for a row crossed by a cable definition line — both "set via
    /// canvas now," the same rule Wire# already follows.</summary>
    public void CommitConnectionEdit(Connection connection)
    {
        _session.UpdateConnectionEndpoints(connection.Id, connection.FromDevicePinId, connection.ToDevicePinId);

        var needsRefresh = false;

        if (ConnectionIdsWithCableLineCrossing.Contains(connection.Id))
        {
            needsRefresh = true;
        }
        else
        {
            _session.UpdateConnectionCable(connection.Id, connection.CableId, connection.CableCoreId);
        }

        if (ConnectionIdsWithDefinitionPoint.Contains(connection.Id))
        {
            needsRefresh = true;
        }
        else
        {
            _session.UpdateConnectionColor(connection.Id, connection.Color);
            _session.UpdateConnectionCrossSection(connection.Id, connection.CrossSectionMm2);
        }

        if (needsRefresh) Refresh();
    }
}
