using System.Collections.ObjectModel;
using System.Windows;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Ecad.Core.Models;
using Ecad.Data;
using Ecad.Data.Repositories;
using Microsoft.Data.Sqlite;

namespace Ecad.App.ViewModels;

/// <summary>A Device's grid-display shape: the base fields plus its assigned Part's ExternalKey
/// (resolved from the project's own cached Part copy, ADR-003/ADR-012) — read-only, since the
/// Library DB's Part.Id (used to pick a Part) and the project-local Part.Id (stored on the Device)
/// are different numbers and can't be reconciled through a single two-way-bound column.</summary>
public sealed class DeviceRow
{
    public long Id { get; set; }
    public string? FunctionSegment { get; set; }
    public string? LocationSegment { get; set; }
    public string DeviceTagSegment { get; set; } = string.Empty;
    public long? PartId { get; set; }
    public string? PartExternalKey { get; set; }
}

/// <summary>
/// M8 Devices grid (Section 6.2): edit devices and pins, and bulk-assign Parts, without drawing
/// anything on a schematic page. Per ADR-011, this grid does NOT create new Devices — a Device is
/// only generated by placing a symbol on the canvas (mimicking EPLAN's graphics-first workflow);
/// the grid is an edit/bulk-edit view over data that already originated there. Opens its own
/// Library DB connection for the read-only Part reference list, same pattern as PartsLibraryViewModel.
/// Inline tag edits are NOT uniqueness-checked the way DeviceTagDialog's canvas flow is (Section
/// 6.1) — an accepted simplification for this grid, matching the project's precedent of noting
/// permissive gaps rather than building new validation UI for them (see ADR-008's attach-flow note).
/// </summary>
public sealed partial class DevicesGridViewModel : ObservableObject, IDisposable
{
    private readonly ProjectSession _session;
    private readonly SqliteConnection _libraryConnection;
    private readonly PartRepository _libraryParts;
    private readonly bool _interruptionPointsOnly;

    /// <summary>False for the Interruption Points Navigator — an interruption point is a navigation
    /// aid, not a physical component, so a manufacturer Part has no meaning for it. Bound by
    /// DevicesNavigatorView to hide the Part-assign header entirely rather than leave a
    /// never-useful control visible.</summary>
    public bool SupportsPartAssignment => !_interruptionPointsOnly;

    public ObservableCollection<DeviceRow> Devices { get; } = [];
    public ObservableCollection<DeviceRow> SelectedDevices { get; } = [];
    public ObservableCollection<Part> AllParts { get; } = [];

    [ObservableProperty]
    private Part? _bulkAssignPart;

    /// <summary>Raised by NavigateToDevice (the Devices Navigator's double-click action) — carries
    /// (PageId, PlacementId), same shape as SchematicPageViewModel.NavigateToPageRequested, wired by
    /// MainViewModel to the same OpenOrFocusPageTab entry point cross-reference navigation uses.</summary>
    public event Action<long, long>? NavigateToPageRequested;

    /// <summary>interruptionPointsOnly selects which of the two exact-complement data sources this
    /// instance shows — MainViewModel creates one instance of each (DevicesNavigator/
    /// InterruptionPointsNavigator), sharing every command/dialog since renaming, Part-assigning, and
    /// cascade-deleting are equally valid operations on either kind.</summary>
    public DevicesGridViewModel(ProjectSession session, bool interruptionPointsOnly = false)
    {
        _session = session;
        _interruptionPointsOnly = interruptionPointsOnly;
        _libraryConnection = LibraryDatabase.Open();
        _libraryParts = new PartRepository(_libraryConnection);
        foreach (var part in _libraryParts.GetAllParts()) AllParts.Add(part);
        Refresh();
    }

    public void Refresh()
    {
        Devices.Clear();
        var devices = _interruptionPointsOnly ? _session.GetAllInterruptionPointDevices() : _session.GetAllRealDevices();
        foreach (var device in devices)
        {
            Devices.Add(new DeviceRow
            {
                Id = device.Id,
                FunctionSegment = device.FunctionSegment,
                LocationSegment = device.LocationSegment,
                DeviceTagSegment = device.DeviceTagSegment,
                PartId = device.PartId,
                PartExternalKey = device.PartId is { } partId ? _session.GetCachedPart(partId)?.ExternalKey : null,
            });
        }
    }

    /// <summary>M8 grid deletes have no undo (ADR-010). Deleting a Device here is a real, drastic
    /// action, not a data-only row removal — it cascades to every Placement (symbol) of this Device
    /// on every schematic page, and their dependent Connections (ADR-015: Devices/Cables are parts
    /// with independent identity, so removing one removes it everywhere it's drawn). The
    /// confirmation makes that scope explicit.</summary>
    [RelayCommand(CanExecute = nameof(HasSelection))]
    private void DeleteSelected()
    {
        var result = MessageBox.Show(
            $"Delete {SelectedDevices.Count} selected device(s)? This removes them — and every symbol placed for them on any schematic page — permanently. This cannot be undone.",
            "Confirm Delete", MessageBoxButton.YesNo, MessageBoxImage.Warning);
        if (result != MessageBoxResult.Yes) return;

        foreach (var device in SelectedDevices.ToList()) _session.DeleteDeviceCascade(device.Id);
    }

    /// <summary>Resolves the selected Library Part into this project's own cached copy first
    /// (ADR-012 — Device.PartId's FK only ever points at the project-local Part table, never the
    /// Library DB directly) before writing it to every selected Device.</summary>
    [RelayCommand(CanExecute = nameof(HasSelection))]
    private void ApplyBulkAssignPart()
    {
        long? projectLocalPartId = BulkAssignPart is null ? null : _session.EnsurePartCached(BulkAssignPart.Id);
        _session.BulkUpdateDevicePart(SelectedDevices.Select(d => d.Id).ToList(), projectLocalPartId);
    }

    private bool HasSelection() => SelectedDevices.Count > 0;

    /// <summary>Called by the view's SelectionChanged handler — DataGrid.SelectedItems isn't
    /// two-way bindable, so the code-behind syncs SelectedDevices and then calls this to requery
    /// the selection-dependent commands (same convention SchematicPageWindow uses for mouse/keyboard).</summary>
    public void NotifySelectionChanged()
    {
        DeleteSelectedCommand.NotifyCanExecuteChanged();
        ApplyBulkAssignPartCommand.NotifyCanExecuteChanged();
    }

    /// <summary>Called by the view after a DataGrid row edit commits, to persist the in-memory edit
    /// back to the database. Only Function/Location/Tag are inline-editable here — Part assignment
    /// goes through ApplyBulkAssignPart (works for a single selected row too), since it needs the
    /// Library-to-project Part-caching step above.</summary>
    public void CommitDeviceEdit(DeviceRow row) =>
        _session.RenameDeviceTag(row.Id, row.FunctionSegment, row.LocationSegment, row.DeviceTagSegment);

    /// <summary>A Device has no direct page of its own — this resolves to the placement on its
    /// earliest page (project order) among possibly several, and asks whoever's listening
    /// (MainViewModel) to jump there. A multi-placement device's other placements stay reachable
    /// from there via the canvas's own Ctrl+Click cross-reference navigation, same as today.</summary>
    public void NavigateToDevice(DeviceRow device)
    {
        var target = _session.GetFirstPlacementForDevice(device.Id);
        if (target is not null) NavigateToPageRequested?.Invoke(target.PageId, target.PlacementId);
    }

    public void Dispose() => _libraryConnection.Dispose();
}
