using Dapper;
using Ecad.Core.Enums;
using Ecad.Core.Models;
using Ecad.Data.Repositories;
using Microsoft.Data.Sqlite;
using Xunit;

namespace Ecad.Data.Tests;

public class ProjectSessionGridEditingTests
{
    private static ProjectSession NewSession(TempSqliteFile file) =>
        ProjectSession.Create(file.Path, new Project { Name = "Test", CreatedAtUtc = DateTimeOffset.UtcNow });

    /// <summary>Device.PartId is a real FK into Part(Id) (the project-local cached Part, ADR-003) —
    /// a non-null assignment needs a real Part row to satisfy it, so this inserts a minimal one via a
    /// second connection to the same file rather than pulling in the EPLAN import pipeline.</summary>
    private static long InsertTestPart(TempSqliteFile file)
    {
        using var connection = new SqliteConnection($"Data Source={file.Path}");
        connection.Open();
        return connection.ExecuteScalar<long>(
            "INSERT INTO Part (ExternalKey, CreatedAtUtc, UpdatedAtUtc) VALUES ('TEST-PART', @now, @now) RETURNING Id;",
            new { now = DateTimeOffset.UtcNow.ToString("O") });
    }

    /// <summary>Per ADR-011, ProjectSession no longer exposes a way to create a Device with zero
    /// Placements — a Device is only ever generated by placing a symbol on the canvas. CanDeleteDevice/
    /// DeleteDevice's zero-placement branch is kept only as a defensive cleanup path (e.g. for legacy
    /// data), so exercising it here goes around ProjectSession entirely via a second raw connection to
    /// the same file, the same way InsertTestPart does.</summary>
    private static long InsertBareDeviceDirect(TempSqliteFile file, long projectId, string tag)
    {
        using var connection = new SqliteConnection($"Data Source={file.Path}");
        connection.Open();
        return new DeviceRepository(connection).InsertDevice(new Device { ProjectId = projectId, DeviceTagSegment = tag });
    }

    [Fact]
    public void UpdateDevicePart_SetsAndClearsPartId()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var page = session.AddPage(new Page { PageNumberSegment = "1" });
        var placed = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X1");
        var partId = InsertTestPart(file);

        session.UpdateDevicePart(placed.DeviceId, partId);
        Assert.Equal(partId, session.GetDevice(placed.DeviceId)!.PartId);

        session.UpdateDevicePart(placed.DeviceId, null);
        Assert.Null(session.GetDevice(placed.DeviceId)!.PartId);
    }

    [Fact]
    public void BulkUpdateDevicePart_AppliesToAllSelected_RaisesPlacementsChangedExactlyOnce()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var page = session.AddPage(new Page { PageNumberSegment = "1" });
        var a = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X1");
        var b = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 40, 0, null, null, "X2");
        var c = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 80, 0, null, null, "X3");
        var partId = InsertTestPart(file);

        var raiseCount = 0;
        session.PlacementsChanged += () => raiseCount++;

        session.BulkUpdateDevicePart([a.DeviceId, b.DeviceId, c.DeviceId], partId);

        Assert.Equal(1, raiseCount);
        Assert.All(new[] { a.DeviceId, b.DeviceId, c.DeviceId }, id => Assert.Equal(partId, session.GetDevice(id)!.PartId));
    }

    [Fact]
    public void DeleteDeviceCascade_RemovesDeviceAndAllPlacementsAcrossPages()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var page1 = session.AddPage(new Page { PageNumberSegment = "1" });
        var page2 = session.AddPage(new Page { PageNumberSegment = "2" });
        var placementOnPage1 = session.PlaceSymbol(page1.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X1");
        var placementOnPage2 = session.PlaceSymbolOnExistingDevice(placementOnPage1.DeviceId, page2.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0);

        session.DeleteDeviceCascade(placementOnPage1.DeviceId);

        Assert.Null(session.GetDevice(placementOnPage1.DeviceId));
        Assert.Empty(session.GetPlacements(page1.Id));
        Assert.Empty(session.GetPlacements(page2.Id));
    }

    [Fact]
    public void DeleteDeviceCascade_DeletesDependentConnections_RaisesEachEventOnceForTheWholeBatch()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var page1 = session.AddPage(new Page { PageNumberSegment = "1" });
        var page2 = session.AddPage(new Page { PageNumberSegment = "2" });
        var a = session.PlaceSymbol(page1.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X1");
        var aOnPage2 = session.PlaceSymbolOnExistingDevice(a.DeviceId, page2.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0);
        var b = session.PlaceSymbol(page1.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 40, 0, null, null, "X2");
        var c = session.PlaceSymbol(page2.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 40, 0, null, null, "X3");
        session.CreateConnection(session.GetPlacementPins(a.Id).Single().DevicePinId, session.GetDevicePins(b.DeviceId).Single().Id);
        session.CreateConnection(session.GetPlacementPins(aOnPage2.Id).Single().DevicePinId, session.GetDevicePins(c.DeviceId).Single().Id);

        var placementsChangedCount = 0;
        var connectionsChangedCount = 0;
        session.PlacementsChanged += () => placementsChangedCount++;
        session.ConnectionsChanged += () => connectionsChangedCount++;

        session.DeleteDeviceCascade(a.DeviceId);

        Assert.Equal(1, placementsChangedCount);
        Assert.Equal(1, connectionsChangedCount);
        Assert.Empty(session.GetAllConnections());
    }

    [Fact]
    public void DeleteDeviceCascade_WithZeroPlacements_StillDeletesTheDevice()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var noPlacements = InsertBareDeviceDirect(file, session.CurrentProject.Id, "X2");

        session.DeleteDeviceCascade(noPlacements);

        Assert.Null(session.GetDevice(noPlacements));
    }

    [Fact]
    public void GetAllRealDevices_And_GetAllInterruptionPointDevices_PartitionCorrectly()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var page = session.AddPage(new Page { PageNumberSegment = "1" });

        var real = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X1");
        var interruption = session.PlaceSymbol(page.Id, "InterruptionPoint", null, "SymbolLibrary/InterruptionPoint.svg", "References", ["1", "2"], 100, 0, null, null, "=1");
        // Mixed: an interruption-point placement plus a real-component placement on the same Device
        // — should be classified as real, not interruption-point-only (ADR-024's stated rule).
        var mixed = session.PlaceSymbol(page.Id, "InterruptionPoint", null, "SymbolLibrary/InterruptionPoint.svg", "References", ["1", "2"], 200, 0, null, null, "=2");
        session.PlaceSymbolOnExistingDevice(mixed.DeviceId, page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 240, 0);

        var realDevices = session.GetAllRealDevices();
        var interruptionDevices = session.GetAllInterruptionPointDevices();

        Assert.Contains(realDevices, d => d.Id == real.DeviceId);
        Assert.Contains(realDevices, d => d.Id == mixed.DeviceId);
        Assert.DoesNotContain(realDevices, d => d.Id == interruption.DeviceId);

        Assert.Contains(interruptionDevices, d => d.Id == interruption.DeviceId);
        Assert.DoesNotContain(interruptionDevices, d => d.Id == real.DeviceId);
        Assert.DoesNotContain(interruptionDevices, d => d.Id == mixed.DeviceId);
    }

    [Fact]
    public void AddDevicePin_UpdateDevicePin_RoundTrip()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var page = session.AddPage(new Page { PageNumberSegment = "1" });
        var placed = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X1");

        var pinId = session.AddDevicePin(placed.DeviceId, "A1", "Coil", null);
        var pin = session.GetDevicePins(placed.DeviceId).Single(p => p.Id == pinId);
        pin.Name = "A2";
        pin.Function = "Coil+";
        session.UpdateDevicePin(pin);

        var updated = session.GetDevicePins(placed.DeviceId).Single(p => p.Id == pinId);
        Assert.Equal("A2", updated.Name);
        Assert.Equal("Coil+", updated.Function);
    }

    [Fact]
    public void CanDeleteDevicePin_FalseWhenWired_TrueOtherwise()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var page = session.AddPage(new Page { PageNumberSegment = "1" });
        var a = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X1");
        var b = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 40, 0, null, null, "X2");
        var aPin = session.GetDevicePins(a.DeviceId).Single();
        var bPin = session.GetDevicePins(b.DeviceId).Single();

        Assert.True(session.CanDeleteDevicePin(aPin.Id));

        session.CreateConnection(aPin.Id, bPin.Id);

        Assert.False(session.CanDeleteDevicePin(aPin.Id));
    }

    [Fact]
    public void DeleteDevicePin_ThrowsWhenWired()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var page = session.AddPage(new Page { PageNumberSegment = "1" });
        var a = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X1");
        var b = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 40, 0, null, null, "X2");
        var aPin = session.GetDevicePins(a.DeviceId).Single();
        var bPin = session.GetDevicePins(b.DeviceId).Single();
        session.CreateConnection(aPin.Id, bPin.Id);

        Assert.Throws<InvalidOperationException>(() => session.DeleteDevicePin(aPin.Id));
    }

    [Fact]
    public void GetAllConnections_ReturnsProjectScopedAcrossMultiplePages()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var page1 = session.AddPage(new Page { PageNumberSegment = "1" });
        var page2 = session.AddPage(new Page { PageNumberSegment = "2" });
        var a = session.PlaceSymbol(page1.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X1");
        var b = session.PlaceSymbol(page1.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 40, 0, null, null, "X2");
        var c = session.PlaceSymbol(page2.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X3");
        var d = session.PlaceSymbol(page2.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 40, 0, null, null, "X4");
        var conn1 = session.CreateConnection(session.GetDevicePins(a.DeviceId).Single().Id, session.GetDevicePins(b.DeviceId).Single().Id);
        var conn2 = session.CreateConnection(session.GetDevicePins(c.DeviceId).Single().Id, session.GetDevicePins(d.DeviceId).Single().Id);

        var all = session.GetAllConnections();

        Assert.Equal(2, all.Count);
        Assert.Contains(all, c => c.Id == conn1.Id);
        Assert.Contains(all, c => c.Id == conn2.Id);
    }

    [Fact]
    public void UpdateConnectionEndpoints_RewiresFromAndTo()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var page = session.AddPage(new Page { PageNumberSegment = "1" });
        var a = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X1");
        var b = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 40, 0, null, null, "X2");
        var c = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 80, 0, null, null, "X3");
        var aPin = session.GetDevicePins(a.DeviceId).Single();
        var bPin = session.GetDevicePins(b.DeviceId).Single();
        var cPin = session.GetDevicePins(c.DeviceId).Single();
        var connection = session.CreateConnection(aPin.Id, bPin.Id);

        session.UpdateConnectionEndpoints(connection.Id, aPin.Id, cPin.Id);

        Assert.True(session.AreConnected(aPin.Id, cPin.Id));
        Assert.False(session.AreConnected(aPin.Id, bPin.Id));
    }

    [Fact]
    public void UpdateConnectionColor_UpdateConnectionCrossSection_LeaveOtherFieldsUnchanged()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var page = session.AddPage(new Page { PageNumberSegment = "1" });
        var a = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X1");
        var b = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 40, 0, null, null, "X2");
        var connection = session.CreateConnection(session.GetDevicePins(a.DeviceId).Single().Id, session.GetDevicePins(b.DeviceId).Single().Id);
        var originalWireNumber = session.GetAllConnections().Single(c => c.Id == connection.Id).WireNumber;

        session.UpdateConnectionColor(connection.Id, "RD");
        session.UpdateConnectionCrossSection(connection.Id, 1.5);

        var updated = session.GetAllConnections().Single(c => c.Id == connection.Id);
        Assert.Equal("RD", updated.Color);
        Assert.Equal(1.5, updated.CrossSectionMm2);
        Assert.Equal(originalWireNumber, updated.WireNumber);
    }

    [Fact]
    public void BulkUpdateConnectionColor_AppliesToAllSelected_RaisesConnectionsChangedOnce()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var page = session.AddPage(new Page { PageNumberSegment = "1" });
        var a = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X1");
        var b = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 40, 0, null, null, "X2");
        var c = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 80, 0, null, null, "X3");
        var d = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 120, 0, null, null, "X4");
        var conn1 = session.CreateConnection(session.GetDevicePins(a.DeviceId).Single().Id, session.GetDevicePins(b.DeviceId).Single().Id);
        var conn2 = session.CreateConnection(session.GetDevicePins(c.DeviceId).Single().Id, session.GetDevicePins(d.DeviceId).Single().Id);

        var raiseCount = 0;
        session.ConnectionsChanged += () => raiseCount++;

        session.BulkUpdateConnectionColor([conn1.Id, conn2.Id], "BU");

        Assert.Equal(1, raiseCount);
        Assert.All(session.GetAllConnections(), c => Assert.Equal("BU", c.Color));
    }

    [Fact]
    public void BulkUpdateConnectionCrossSection_AppliesToAllSelected()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var page = session.AddPage(new Page { PageNumberSegment = "1" });
        var a = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X1");
        var b = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 40, 0, null, null, "X2");
        var conn = session.CreateConnection(session.GetDevicePins(a.DeviceId).Single().Id, session.GetDevicePins(b.DeviceId).Single().Id);

        session.BulkUpdateConnectionCrossSection([conn.Id], 2.5);

        Assert.Equal(2.5, session.GetAllConnections().Single().CrossSectionMm2);
    }

    [Fact]
    public void CreateCable_SetsProjectId_ScopedCorrectlyAcrossTwoProjects()
    {
        using var fileA = new TempSqliteFile();
        using var fileB = new TempSqliteFile();
        using var sessionA = NewSession(fileA);
        using var sessionB = NewSession(fileB);

        sessionA.CreateCable(new Cable { Tag = "-W1" });
        sessionB.CreateCable(new Cable { Tag = "-W2" });

        Assert.Equal("-W1", sessionA.GetAllCables().Single().Tag);
        Assert.Equal("-W2", sessionB.GetAllCables().Single().Tag);
    }

    [Fact]
    public void GetAllCables_IncludesOrphanCableWithNoConnections()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);

        var cable = session.CreateCable(new Cable { Tag = "-W1" });

        Assert.Contains(session.GetAllCables(), c => c.Id == cable.Id);
    }

    [Fact]
    public void UpdateCable_UpdatesFields()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var cable = session.CreateCable(new Cable { Tag = "-W1" });

        cable.Tag = "-W1-renamed";
        cable.LengthMm = 1500;
        cable.EndTypeClassification = "FER-FER";
        session.UpdateCable(cable);

        var updated = session.GetAllCables().Single();
        Assert.Equal("-W1-renamed", updated.Tag);
        Assert.Equal(1500, updated.LengthMm);
        Assert.Equal("FER-FER", updated.EndTypeClassification);
    }

    [Fact]
    public void CanDeleteCable_FalseWhenReferencedByConnection_TrueOtherwise()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var page = session.AddPage(new Page { PageNumberSegment = "1" });
        var a = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X1");
        var b = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 40, 0, null, null, "X2");
        var connection = session.CreateConnection(session.GetDevicePins(a.DeviceId).Single().Id, session.GetDevicePins(b.DeviceId).Single().Id);
        var cable = session.CreateCable(new Cable { Tag = "-W1" });

        Assert.True(session.CanDeleteCable(cable.Id));

        session.UpdateConnectionCable(connection.Id, cable.Id, null);

        Assert.False(session.CanDeleteCable(cable.Id));
    }

    [Fact]
    public void DeleteCable_ThrowsWhenReferenced()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var page = session.AddPage(new Page { PageNumberSegment = "1" });
        var a = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X1");
        var b = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 40, 0, null, null, "X2");
        var connection = session.CreateConnection(session.GetDevicePins(a.DeviceId).Single().Id, session.GetDevicePins(b.DeviceId).Single().Id);
        var cable = session.CreateCable(new Cable { Tag = "-W1" });
        session.UpdateConnectionCable(connection.Id, cable.Id, null);

        Assert.Throws<InvalidOperationException>(() => session.DeleteCable(cable.Id));
    }

    [Fact]
    public void GetFirstConnectionPageForCable_WiredOnTwoPages_ReturnsTheOneOnTheEarliestPage()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var earlyPage = session.AddPage(new Page { PageNumberSegment = "1" });
        var latePage = session.AddPage(new Page { PageNumberSegment = "2" });

        // Assigned to the later page first, then the earlier page second — assignment order is the
        // opposite of page order, proving the lookup follows Page.SortOrder, not Connection.Id.
        var lateA = session.PlaceSymbol(latePage.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X1");
        var lateB = session.PlaceSymbol(latePage.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 40, 0, null, null, "X2");
        var lateConnection = session.CreateConnection(session.GetDevicePins(lateA.DeviceId).Single().Id, session.GetDevicePins(lateB.DeviceId).Single().Id);

        var earlyA = session.PlaceSymbol(earlyPage.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X3");
        var earlyB = session.PlaceSymbol(earlyPage.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 40, 0, null, null, "X4");
        var earlyConnection = session.CreateConnection(session.GetDevicePins(earlyA.DeviceId).Single().Id, session.GetDevicePins(earlyB.DeviceId).Single().Id);

        var cable = session.CreateCable(new Cable { Tag = "-W1" });
        session.UpdateConnectionCable(lateConnection.Id, cable.Id, null);
        session.UpdateConnectionCable(earlyConnection.Id, cable.Id, null);

        var target = session.GetFirstConnectionPageForCable(cable.Id);

        Assert.NotNull(target);
        Assert.Equal(earlyPage.Id, target!.PageId);
    }

    [Fact]
    public void GetFirstConnectionPageForCable_NoConnectionsAssigned_ReturnsNull()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var cable = session.CreateCable(new Cable { Tag = "-W1" });

        Assert.Null(session.GetFirstConnectionPageForCable(cable.Id));
    }

    [Fact]
    public void DeleteCable_SucceedsWhenUnreferenced_CascadesCableCores()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var cable = session.CreateCable(new Cable { Tag = "-W1" });
        session.AddCableCore(cable.Id, new CableCore { CoreNumber = 1 });

        session.DeleteCable(cable.Id);

        Assert.DoesNotContain(session.GetAllCables(), c => c.Id == cable.Id);
    }

    [Fact]
    public void AddCableCore_UpdateCableCore_RoundTrip()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var cable = session.CreateCable(new Cable { Tag = "-W1" });

        var core = session.AddCableCore(cable.Id, new CableCore { CoreNumber = 1, Color = "BN" });
        core.Color = "BU";
        core.CrossSectionMm2 = 0.75;
        session.UpdateCableCore(core);

        var updated = session.GetCableCores(cable.Id).Single();
        Assert.Equal("BU", updated.Color);
        Assert.Equal(0.75, updated.CrossSectionMm2);
    }

    [Fact]
    public void DeleteCableCore_ClearsCableCoreIdOnReferencingConnections_ButLeavesCableIdIntact()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var page = session.AddPage(new Page { PageNumberSegment = "1" });
        var a = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X1");
        var b = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 40, 0, null, null, "X2");
        var connection = session.CreateConnection(session.GetDevicePins(a.DeviceId).Single().Id, session.GetDevicePins(b.DeviceId).Single().Id);
        var cable = session.CreateCable(new Cable { Tag = "-W1" });
        var core = session.AddCableCore(cable.Id, new CableCore { CoreNumber = 1 });
        session.UpdateConnectionCable(connection.Id, cable.Id, core.Id);

        session.DeleteCableCore(core.Id);

        var updated = session.GetAllConnections().Single(c => c.Id == connection.Id);
        Assert.Null(updated.CableCoreId);
        Assert.Equal(cable.Id, updated.CableId);
    }

    [Fact]
    public void CablesChanged_FiresOnCableAndCableCoreMutations()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var raiseCount = 0;
        session.CablesChanged += () => raiseCount++;

        var cable = session.CreateCable(new Cable { Tag = "-W1" });
        Assert.Equal(1, raiseCount);

        session.UpdateCable(cable);
        Assert.Equal(2, raiseCount);

        var core = session.AddCableCore(cable.Id, new CableCore { CoreNumber = 1 });
        Assert.Equal(3, raiseCount);

        session.UpdateCableCore(core);
        Assert.Equal(4, raiseCount);

        session.DeleteCableCore(core.Id);
        Assert.Equal(5, raiseCount);
    }

    [Fact]
    public void EnsurePartCached_CopiesPartIntoProjectDatabase_ReturnsProjectLocalId()
    {
        using var libraryFile = new TempSqliteFile();
        using var projectFile = new TempSqliteFile();
        using var libraryConnection = LibraryDatabase.Open(libraryFile.Path);
        var libraryParts = new PartRepository(libraryConnection);
        var libraryPart = new Part { ExternalKey = "ABC-123", Description1 = "Test Part" };
        libraryParts.UpsertByExternalKey(libraryPart, DateTimeOffset.UtcNow);
        using var session = NewSession(projectFile);

        var projectLocalId = session.EnsurePartCached(libraryPart.Id, libraryFile.Path);

        var cached = session.GetCachedPart(projectLocalId);
        Assert.NotNull(cached);
        Assert.Equal("ABC-123", cached!.ExternalKey);
        Assert.Equal("Test Part", cached.Description1);
    }

    [Fact]
    public void EnsurePartCached_IsIdempotent_ReturnsSameProjectLocalIdOnSecondCall()
    {
        using var libraryFile = new TempSqliteFile();
        using var projectFile = new TempSqliteFile();
        using var libraryConnection = LibraryDatabase.Open(libraryFile.Path);
        var libraryPart = new Part { ExternalKey = "ABC-123" };
        new PartRepository(libraryConnection).UpsertByExternalKey(libraryPart, DateTimeOffset.UtcNow);
        using var session = NewSession(projectFile);

        var firstId = session.EnsurePartCached(libraryPart.Id, libraryFile.Path);
        var secondId = session.EnsurePartCached(libraryPart.Id, libraryFile.Path);

        Assert.Equal(firstId, secondId);
    }

    [Fact]
    public void EnsurePartCached_ResolvesManufacturerOrganizationByExternalKeyIntoProjectDatabase()
    {
        using var libraryFile = new TempSqliteFile();
        using var projectFile = new TempSqliteFile();
        using var libraryConnection = LibraryDatabase.Open(libraryFile.Path);
        var libraryParts = new PartRepository(libraryConnection);
        var manufacturerId = libraryParts.GetOrCreateOrganization("Siemens", "SIE");
        var libraryPart = new Part { ExternalKey = "ABC-123", ManufacturerId = manufacturerId };
        libraryParts.UpsertByExternalKey(libraryPart, DateTimeOffset.UtcNow);
        using var session = NewSession(projectFile);

        var projectLocalId = session.EnsurePartCached(libraryPart.Id, libraryFile.Path);

        var cachedManufacturerId = session.GetCachedPart(projectLocalId)!.ManufacturerId;
        Assert.NotNull(cachedManufacturerId);
        using var projectConnection = new SqliteConnection($"Data Source={projectFile.Path}");
        projectConnection.Open();
        var projectOrganization = new PartRepository(projectConnection).GetOrganization(cachedManufacturerId!.Value);
        Assert.NotNull(projectOrganization);
        Assert.Equal("Siemens", projectOrganization!.Name);
        Assert.Equal("SIE", projectOrganization.ExternalKey);
    }

    /// <summary>Regression test for the exact crash a live user hit: assigning a Library Part
    /// straight to Device.PartId without first caching it into the project throws SQLite Error 19
    /// (FOREIGN KEY constraint failed), since Device.PartId only ever references the project's own
    /// Part table (ADR-003/ADR-012), never the Library DB directly.</summary>
    [Fact]
    public void UpdateDevicePart_WithLibraryPartCachedFirst_DoesNotThrowForeignKeyViolation()
    {
        using var libraryFile = new TempSqliteFile();
        using var projectFile = new TempSqliteFile();
        using var libraryConnection = LibraryDatabase.Open(libraryFile.Path);
        var libraryPart = new Part { ExternalKey = "ABC-123" };
        new PartRepository(libraryConnection).UpsertByExternalKey(libraryPart, DateTimeOffset.UtcNow);
        using var session = NewSession(projectFile);
        var page = session.AddPage(new Page { PageNumberSegment = "1" });
        var placed = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X1");

        var projectLocalId = session.EnsurePartCached(libraryPart.Id, libraryFile.Path);
        session.UpdateDevicePart(placed.DeviceId, projectLocalId);

        Assert.Equal(projectLocalId, session.GetDevice(placed.DeviceId)!.PartId);
    }

    [Fact]
    public void UpdateConnectionEndTermination_SetsAllFields_WithoutAffectingTheOtherEnd()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var page = session.AddPage(new Page { PageNumberSegment = "1" });
        var a = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X1");
        var b = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 40, 0, null, null, "X2");
        var connection = session.CreateConnection(session.GetDevicePins(a.DeviceId).Single().Id, session.GetDevicePins(b.DeviceId).Single().Id);
        var partId = InsertTestPart(file);
        var ends = session.GetAllConnectionEndsWithContext().Where(e => e.ConnectionId == connection.Id).ToList();
        var fromEnd = ends.Single(e => e.End == ConnectionEndDesignator.From);
        var toEnd = ends.Single(e => e.End == ConnectionEndDesignator.To);

        session.UpdateConnectionEndTermination(fromEnd.Id, true, TerminationType.Ferrule, partId, 8.5);

        var updated = session.GetAllConnectionEndsWithContext().Where(e => e.ConnectionId == connection.Id).ToList();
        var updatedFromEnd = updated.Single(e => e.End == ConnectionEndDesignator.From);
        var untouchedToEnd = updated.Single(e => e.End == ConnectionEndDesignator.To);
        Assert.True(updatedFromEnd.TerminationEnabled);
        Assert.Equal(TerminationType.Ferrule, updatedFromEnd.TerminationType);
        Assert.Equal(partId, updatedFromEnd.TerminationPartId);
        Assert.Equal(8.5, updatedFromEnd.StrippingLengthMm);
        Assert.False(untouchedToEnd.TerminationEnabled);
        Assert.Equal(TerminationType.None, untouchedToEnd.TerminationType);
        Assert.Null(untouchedToEnd.TerminationPartId);
        Assert.Equal(toEnd.Id, untouchedToEnd.Id);
    }

    [Fact]
    public void UpdateConnectionEndTermination_CanClearPartAndDisableTermination()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var page = session.AddPage(new Page { PageNumberSegment = "1" });
        var a = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X1");
        var b = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 40, 0, null, null, "X2");
        var connection = session.CreateConnection(session.GetDevicePins(a.DeviceId).Single().Id, session.GetDevicePins(b.DeviceId).Single().Id);
        var partId = InsertTestPart(file);
        var endId = session.GetAllConnectionEndsWithContext().First(e => e.ConnectionId == connection.Id).Id;
        session.UpdateConnectionEndTermination(endId, true, TerminationType.Ferrule, partId, 8.5);

        session.UpdateConnectionEndTermination(endId, false, TerminationType.None, null, null);

        var cleared = session.GetAllConnectionEndsWithContext().Single(e => e.Id == endId);
        Assert.False(cleared.TerminationEnabled);
        Assert.Equal(TerminationType.None, cleared.TerminationType);
        Assert.Null(cleared.TerminationPartId);
        Assert.Null(cleared.StrippingLengthMm);
    }

    [Fact]
    public void GetAllConnectionEndsWithContext_ReturnsWireNumberAndCrossSectionFromParentConnection()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var page = session.AddPage(new Page { PageNumberSegment = "1" });
        var a = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X1");
        var b = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 40, 0, null, null, "X2");
        var connection = session.CreateConnection(session.GetDevicePins(a.DeviceId).Single().Id, session.GetDevicePins(b.DeviceId).Single().Id);
        session.PlaceDefinitionPoint(page.Id, 20, 0, "W42", null, null, connection.Id);
        session.UpdateConnectionCrossSection(connection.Id, 1.5);

        var ends = session.GetAllConnectionEndsWithContext().Where(e => e.ConnectionId == connection.Id).ToList();

        Assert.Equal(2, ends.Count);
        Assert.All(ends, e => Assert.Equal("W42", e.WireNumber));
        Assert.All(ends, e => Assert.Equal(1.5, e.CrossSectionMm2));
    }

    [Fact]
    public void GetAllConnectionEndsWithContext_ReturnsProjectScopedAcrossMultiplePages()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var page1 = session.AddPage(new Page { PageNumberSegment = "1" });
        var page2 = session.AddPage(new Page { PageNumberSegment = "2" });
        var a = session.PlaceSymbol(page1.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X1");
        var b = session.PlaceSymbol(page1.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 40, 0, null, null, "X2");
        var c = session.PlaceSymbol(page2.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X3");
        var d = session.PlaceSymbol(page2.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 40, 0, null, null, "X4");
        session.CreateConnection(session.GetDevicePins(a.DeviceId).Single().Id, session.GetDevicePins(b.DeviceId).Single().Id);
        session.CreateConnection(session.GetDevicePins(c.DeviceId).Single().Id, session.GetDevicePins(d.DeviceId).Single().Id);

        var ends = session.GetAllConnectionEndsWithContext();

        Assert.Equal(4, ends.Count);
    }

    [Fact]
    public void GetAllConnectionEndsWithContext_ReturnsBothEndDesignatorsPerConnection()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var page = session.AddPage(new Page { PageNumberSegment = "1" });
        var a = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X1");
        var b = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 40, 0, null, null, "X2");
        var connection = session.CreateConnection(session.GetDevicePins(a.DeviceId).Single().Id, session.GetDevicePins(b.DeviceId).Single().Id);

        var ends = session.GetAllConnectionEndsWithContext().Where(e => e.ConnectionId == connection.Id).ToList();

        Assert.Single(ends, e => e.End == ConnectionEndDesignator.From);
        Assert.Single(ends, e => e.End == ConnectionEndDesignator.To);
    }

    [Fact]
    public void EnsurePartCached_ReusedForTerminationPart_AssignsProjectLocalIdSuccessfully()
    {
        using var libraryFile = new TempSqliteFile();
        using var projectFile = new TempSqliteFile();
        using var libraryConnection = LibraryDatabase.Open(libraryFile.Path);
        var libraryPart = new Part { ExternalKey = "FER-0.5" };
        new PartRepository(libraryConnection).UpsertByExternalKey(libraryPart, DateTimeOffset.UtcNow);
        using var session = NewSession(projectFile);
        var page = session.AddPage(new Page { PageNumberSegment = "1" });
        var a = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X1");
        var b = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 40, 0, null, null, "X2");
        var connection = session.CreateConnection(session.GetDevicePins(a.DeviceId).Single().Id, session.GetDevicePins(b.DeviceId).Single().Id);
        var endId = session.GetAllConnectionEndsWithContext().First(e => e.ConnectionId == connection.Id).Id;

        var projectLocalId = session.EnsurePartCached(libraryPart.Id, libraryFile.Path);
        session.UpdateConnectionEndTermination(endId, true, TerminationType.Ferrule, projectLocalId, 8);

        Assert.Equal(projectLocalId, session.GetAllConnectionEndsWithContext().Single(e => e.Id == endId).TerminationPartId);
    }

    [Fact]
    public void BulkUpdateConnectionEndPart_AppliesToOnlyTargetedEnds_RaisesConnectionsChangedExactlyOnce()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var page = session.AddPage(new Page { PageNumberSegment = "1" });
        var a = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X1");
        var b = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 40, 0, null, null, "X2");
        var c = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 80, 0, null, null, "X3");
        var d = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 120, 0, null, null, "X4");
        var conn1 = session.CreateConnection(session.GetDevicePins(a.DeviceId).Single().Id, session.GetDevicePins(b.DeviceId).Single().Id);
        var conn2 = session.CreateConnection(session.GetDevicePins(c.DeviceId).Single().Id, session.GetDevicePins(d.DeviceId).Single().Id);
        var partId = InsertTestPart(file);
        var conn1FromEndId = session.GetAllConnectionEndsWithContext().First(e => e.ConnectionId == conn1.Id && e.End == ConnectionEndDesignator.From).Id;
        var conn2FromEndId = session.GetAllConnectionEndsWithContext().First(e => e.ConnectionId == conn2.Id && e.End == ConnectionEndDesignator.From).Id;
        var conn1ToEndId = session.GetAllConnectionEndsWithContext().First(e => e.ConnectionId == conn1.Id && e.End == ConnectionEndDesignator.To).Id;

        var raiseCount = 0;
        session.ConnectionsChanged += () => raiseCount++;

        session.BulkUpdateConnectionEndPart([conn1FromEndId, conn2FromEndId], partId);

        Assert.Equal(1, raiseCount);
        var all = session.GetAllConnectionEndsWithContext();
        Assert.Equal(partId, all.Single(e => e.Id == conn1FromEndId).TerminationPartId);
        Assert.Equal(partId, all.Single(e => e.Id == conn2FromEndId).TerminationPartId);
        Assert.Null(all.Single(e => e.Id == conn1ToEndId).TerminationPartId);
    }

    [Fact]
    public void BulkUpdateConnectionEndPart_WithNullPartId_ClearsAssignment()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var page = session.AddPage(new Page { PageNumberSegment = "1" });
        var a = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X1");
        var b = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 40, 0, null, null, "X2");
        var connection = session.CreateConnection(session.GetDevicePins(a.DeviceId).Single().Id, session.GetDevicePins(b.DeviceId).Single().Id);
        var partId = InsertTestPart(file);
        var endId = session.GetAllConnectionEndsWithContext().First(e => e.ConnectionId == connection.Id).Id;
        session.BulkUpdateConnectionEndPart([endId], partId);

        session.BulkUpdateConnectionEndPart([endId], null);

        Assert.Null(session.GetAllConnectionEndsWithContext().Single(e => e.Id == endId).TerminationPartId);
    }

    [Fact]
    public void CreateConnection_StillCreatesBothEndsWithTerminationOff()
    {
        using var file = new TempSqliteFile();
        using var session = NewSession(file);
        var page = session.AddPage(new Page { PageNumberSegment = "1" });
        var a = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 0, 0, null, null, "X1");
        var b = session.PlaceSymbol(page.Id, "Terminal", null, "SymbolLibrary/Terminal.svg", "Terminals", ["1"], 40, 0, null, null, "X2");

        var connection = session.CreateConnection(session.GetDevicePins(a.DeviceId).Single().Id, session.GetDevicePins(b.DeviceId).Single().Id);

        var ends = session.GetAllConnectionEndsWithContext().Where(e => e.ConnectionId == connection.Id).ToList();
        Assert.Equal(2, ends.Count);
        Assert.All(ends, e => Assert.False(e.TerminationEnabled));
        Assert.All(ends, e => Assert.Equal(TerminationType.None, e.TerminationType));
        Assert.All(ends, e => Assert.Null(e.TerminationPartId));
    }
}
